sudo: false

language: node_js

services:
  - docker

script:
  - docker-compose -f docker-compose.e2e-test.yml up --abort-on-container-exit --exit-code-from backend
  - docker-compose down

notification:
  - emails: false
