sudo: false

language: node_js
sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - docker-compose --version

script:
  - docker-compose up

notification:
  - emails: false
