sudo: false

language: node_js

services:
  - docker

script:
  - docker-compose -f docker-compose.e2e-test.yml up -d
  - docker-compose run backend npm run test
  - docker-compose stop

notification:
  - emails: false
