language: node_js

services:
  - docker

script:
  - docker-compose -f docker-compose.e2e-test.yml up -d
  - docker-compose exec backend echo $COVERALLS_REPO_TOKEN
  - docker-compose exec backend npm run test:coveralls

notification:
  - emails: false
