language: node_js

services:
  - docker

script:
  - docker-compose -f docker-compose.e2e-test.yml up -d
  - docker-compose ps
  - docker-compose exec backend echo $COVERALLS_REPO_TOKEN
  - docker-compose exec backend npm run test-coverage
  - docker-compose cp backend:./app/coverage ./coverage
  - npm i coveralls
  - npx coveralls < coverage/lcov.info

notification:
  - emails: false
