language: node_js

services:
  - docker

script:
  - docker-compose -f docker-compose.e2e-test.yml up -d
  - docker-compose ps
  - docker-compose exec backend npx jest --coverage
  - docker-compose exec backend npm run test:coveralls

notification:
  - emails: false
