language: node_js
node_js:
  - 16

services:
  - docker

script:
  - docker-compose --version
  - docker-compose up -d
  - docker-compose ps
  - docker-compose exec backend echo $COVERALLS_REPO_TOKEN
  - docker-compose exec backend npm run test-coverage
  - docker cp "$(docker-compose ps -q backend)":/app/coverage ./backend/coverage
  - cd backend
  - npm i
  - npx coveralls < coverage/lcov.info

notification:
  - emails: false
