sudo: false

language: node_js

services:
  - docker

script:
  - docker-compose up -f docker-compose.e2e-test.yml --abort-on-container-exit --exit-code-from backend
  - docker-compose down

notification:
  - emails: false
