version: '3'
services:
  app:
    image: mobiler
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_USERNAME=mobilehairdresser
      - MONGODB_PASSWORD=qmf9jrSmcZweK4Cu
      - MONGODB_DATABASE=mobilehairdresser
      - MONGODB_CONNECTION_STRING=mongodb://mongo/mobilehairdresser
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    ports:
      - 27017:27017
